version: '2'
services:
  centos5:
    build: ./centos5
    hostname: centos5
    tty: true
    volumes:
      - './centos5/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/toolbox/scripts/:rw'
      - '../arch/:/usr/local/toolbox/arch/:rw'
  centos6:
    build: ./centos6
    hostname: centos6
    tty: true
    volumes:
      - './centos6/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/toolbox/scripts/:rw'
      - '../arch/:/usr/local/toolbox/arch/:rw'
  centos7:
    build: ./centos7
    hostname: centos7
    tty: true
    volumes:
      - './centos7/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/toolbox/scripts/:rw'
      - '../arch/:/usr/local/toolbox/arch/:rw'
  ubuntu1604:
    build: ./ubuntu1604
    hostname: ubuntu1604
    tty: true
    volumes:
      - './ubuntu1604/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/toolbox/scripts/:rw'
      - '../arch/:/usr/local/toolbox/arch/:rw'
