version: '2'
services:
  centos6:
    image: centos_toolbox:6
    build: ./centos6
    hostname: centos6
    tty: true
    volumes:
      - './centos6/home/:/home/:rw'
      - './centos6/opt/toolbox/:/opt/toolbox/:rw'
      - '../scripts/:/opt/toolbox/workspace/scripts/:rw'
      - '../archives/:/opt/toolbox/workspace/archives/:rw'
  ubuntu1404:
    image: ubuntu_toolbox:14.04
    build: ./ubuntu1404
    hostname: ubuntu1404
    tty: true
    volumes:
      - './ubuntu1404/home/:/home/:rw'
      - './ubuntu1404/opt/toolbox/:/opt/toolbox/:rw'
      - '../scripts/:/opt/toolbox/workspace/scripts/:rw'
      - '../archives/:/opt/toolbox/workspace/archives/:rw'
