version: '2'
services:
  centos6:
    image: centos_toolbox:6
    build: ./centos6
    hostname: centos6
    tty: true
    volumes:
      - './centos6/home/:/home/:rw'
      - './centos6/opt/toolbox/:/opt/toolbox/:rw'
      - '../scripts/:/opt/toolbox/workspace/scripts/:rw'
      - '../archives/:/opt/toolbox/workspace/archives/:rw'
  ubuntu1604:
    image: ubuntu_toolbox:16.04
    build: ./ubuntu1604
    hostname: ubuntu1604
    tty: true
    volumes:
      - './ubuntu1604/home/:/home/:rw'
      - './ubuntu1604/opt/toolbox/:/opt/toolbox/:rw'
      - '../scripts/:/opt/toolbox/workspace/scripts/:rw'
      - '../archives/:/opt/toolbox/workspace/archives/:rw'
