version: '2'
services:
  centos:
    image: centos_toolbox:7.7.1908
    build: centos
    hostname: centos
    tty: true
    volumes:
      - "./centos${PREFIX}/:${PREFIX}/:rw"
      - "../scripts/:${PREFIX}/${WORKSPACE}/scripts/:rw"
      - "../archives/:${PREFIX}/${WORKSPACE}/archives/:rw"
  ubuntu:
    image: ubuntu_toolbox:18.04
    build: ubuntu
    hostname: ubuntu
    tty: true
    volumes:
      - "./ubuntu${PREFIX}/:${PREFIX}/:rw"
      - "../scripts/:${PREFIX}/${WORKSPACE}/scripts/:rw"
      - "../archives/:${PREFIX}/${WORKSPACE}/archives/:rw"
