version: '2'
services:
  centos:
    image: centos_toolbox:6.10
    build: centos
    hostname: centos
    tty: true
    volumes:
      - './centos/opt/toolbox/:/opt/toolbox/:rw'
      - '../scripts/:/opt/toolbox/workspace/scripts/:rw'
      - '../archives/:/opt/toolbox/workspace/archives/:rw'
  ubuntu:
    image: ubuntu_toolbox:16.04
    build: ubuntu
    hostname: ubuntu
    tty: true
    volumes:
      - './ubuntu/opt/toolbox/:/opt/toolbox/:rw'
      - '../scripts/:/opt/toolbox/workspace/scripts/:rw'
      - '../archives/:/opt/toolbox/workspace/archives/:rw'
